seatManage/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views
app_name='seatManage'
urlpatterns = [
    path('', views.index),
    path('add_user', views.add_user, name='add_user'),
    path('update_user',views.update_user,name='update_user'),
    path('select_user',views.select_user,name='select_user'),
    path('search',views.search,name='search'),
    path('stop_time', views.stop_time, name='stop_time'),
    path('start_time', views.start_time, name='start_time'),
    path('manage', views.manage, name='manage'),
    path('vail_seat', views.vail_seat, name='vail_seat')

]

studyRoom/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seatManage/', include('seatManage.urls')),

]

seatManage/models.py
import time

from django.db import models


# Create your models here.
class UserInfo(models.Model):
    id = models.BigAutoField(primary_key=True)
    username = models.CharField(max_length=30, verbose_name="用户姓名")
    user_phone = models.CharField(max_length=30, verbose_name="电话")
    user_sex = models.CharField(max_length=2, verbose_name="用户性别")
    user_fingerprint = models.CharField(max_length=30, verbose_name="用户指纹信息")
    user_seat = models.ForeignKey("Seat", on_delete=models.CASCADE)
    user_card_class = models.CharField(max_length=10, verbose_name="卡种类")
    user_card_number = models.CharField(max_length=15, verbose_name="卡号",default=0)
    card_create_time = models.BigIntegerField(verbose_name="开卡日期")
    card_expiration_time = models.BigIntegerField(verbose_name="卡过期日期")
    modified_time = models.BigIntegerField(verbose_name="修改操作时间")
    info_change_time = models.BigIntegerField(verbose_name="更改信息时间")
    active_day = models.IntegerField(verbose_name="活跃天数",default=0)
    stop_time = models.BigIntegerField(verbose_name="暂停时间",default=0)
    stop_number = models.IntegerField(verbose_name="暂停次数")
    flag = models.IntegerField(verbose_name="过期标志",default=1)
    stop_flag = models.IntegerField(verbose_name='run暂停标志',default=0)


class Seat(models.Model):
    id = models.BigAutoField(primary_key=True)
    seat_number = models.IntegerField()
    img_seat_url = models.CharField(max_length=90,verbose_name="图片地址")


class HistorySeat(models.Model):
    h_id = models.AutoField(primary_key=True)
    user = models.OneToOneField("UserInfo", on_delete=models.CASCADE)
    seat = models.OneToOneField("seat",on_delete=models.CASCADE)

seatManage/views.py
import time
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Seat, UserInfo

HOST = 'http://localhost:8080'

def index(request):
    seat_list = Seat.objects.values('seat_number', 'img_seat_url')
    user = UserInfo.objects.values('id', 'username', 'user_card_class', 'card_create_time', 'user_card_number',
                                   'card_expiration_time', 'user_seat_id', 'stop_flag', 'stop_time', 'flag').filter(
        flag=1)
    seat_list = list(seat_list)
    # 获取当前的时间戳
    curr_time = int(time.time())
    # print(curr_time)
    # 卡是否过期，是flag=0，否，计算剩余多少天
    for user_info in user:
        if user_info.get('card_expiration_time') < curr_time:
            user_info.update({'flag': 0})
            UserInfo.objects.filter(pk=user_info.get('id')).update(flag=0)
        else:
            UserInfo.objects.filter(pk=user_info.get('id')).update(flag=1)
            exp_time = user_info.get('card_expiration_time') - curr_time
            # print(user_info.get('stop_flag'))
            if user_info.get('stop_flag') == 0:
                use_time = curr_time - user_info.get('card_create_time')
                # 获取卡还剩多少天
                rest_day = (exp_time - use_time) // 86400
            elif user_info.get('stop_flag') == 1:
                # print("###")
                stop_time_ = user_info.get('stop_time')
                # print(stop_time_)
                rest_day = (user_info.get('card_expiration_time') - stop_time_) // 86400
            user_info['rest_day'] = rest_day + 1

    for seat_dic in seat_list:
        for user_info in user:
            if seat_dic.get('seat_number') == user_info.get('user_seat_id'):
                seat_dic.update(user_info)
    # print(seat_list)

    return render(request, 'seatManage/index.html', locals())


def add_user(request):
    # ctx = {}
    card_expiration_time = None
    if request.POST:
        user = request.POST
        # print(user)
        card_create_time = int(time.time())
        if user['cardClass'] == '日卡':
            card_expiration_time = (card_create_time + 86400 * 1)
        elif user['cardClass'] == '周卡':
            card_expiration_time = (card_create_time + 86400 * 7)
        elif user['cardClass'] == '月卡':
            card_expiration_time = (card_create_time + 86400 * 31)
        elif user['cardClass'] == '季卡':
            card_expiration_time = (card_create_time + 86400 * 31 * 3)
        elif user['cardClass'] == '半年卡':
            card_expiration_time = (card_create_time + 86400 * 186)
        # print(user)
        user_card_number = int(time.time())
        user_info = UserInfo.objects.create(username=user['username'], user_phone=user['phone'], user_sex=user['sex'],
                                            user_fingerprint=user['fingerPrint'], user_card_class=user['cardClass'],
                                            card_create_time=str(card_create_time), stop_number=0,
                                            card_expiration_time=str(card_expiration_time),
                                            user_card_number=user_card_number,
                                            modified_time=card_create_time, info_change_time=card_create_time,
                                            user_seat_id=user['seat'], flag=1)

    # print(user_info)
    return redirect(HOST+"/seatManage/")


def update_user(request):
    if request.POST:
        user = request.POST

        exp_time = user['date']
        exp_time = int(time.mktime(time.strptime(exp_time[: -1].replace("T", " "), '%Y-%m-%d %H:%M')))
        modified_time = int(time.time())
        info_change_time = int(time.time())
        UserInfo.objects.filter(user_card_number=user['cardNum']).update(user_seat_id=user['updateSeat'],
                                                                         card_expiration_time=exp_time,
                                                                         modified_time=modified_time,
                                                                         info_change_time=info_change_time)
    return redirect(HOST+"/seatManage/")


def timeOf(ts, parttern="%Y-%m-%d %H:%M:%S"):
    try:
        timeArray = time.localtime(int(ts))
        return time.strftime(parttern, timeArray)
    except:
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(ts)))


def select_user(request):
    users = UserInfo.objects.values('id', 'username', 'user_sex', 'user_seat_id', 'user_fingerprint',
                                    'user_card_number',
                                    'user_card_class', 'user_phone', 'card_create_time', 'card_expiration_time',
                                    'modified_time', 'stop_number', 'stop_time', 'flag','stop_flag')
    users = list(users)
    for user_info in users:
        card_create_time = timeOf(user_info.get('card_create_time'))
        card_expiration_time = timeOf(user_info.get('card_expiration_time'))
        modified_time = timeOf(user_info.get('modified_time'))
        if user_info.get('stop_time'):
            stop_time = timeOf(user_info.get('stop_time'))
        else:
            stop_time = 0
        user_info.update({'card_create_time': card_create_time})
        user_info.update({'card_expiration_time': card_expiration_time})
        user_info.update({'modified_time': modified_time})
        user_info.update({'stop_time': stop_time})
        if user_info.get('flag') == 1:
            user_info.update({'flag': '卡正常'})
        else:
            user_info.update({'flag': '卡过期'})
        if user_info.get('stop_flag') == 1:
            user_info.update({'stop_flag': '卡暂停'})
        else:
            user_info.update({'stop_flag': '卡正常'})

    return render(request, 'seatManage/userinfo.html', locals())


def search(request):
    if request.POST:
        user = request.POST
        user = UserInfo.objects.values('id', 'username', 'user_sex', 'user_seat_id', 'user_fingerprint',
                                        'user_card_number',
                                        'user_card_class', 'user_phone', 'card_create_time', 'card_expiration_time',
                                        'modified_time', 'stop_number', 'stop_time', 'flag','stop_flag').filter(user_card_number=user['cardNum'])
        for user_info in user:
            card_create_time = timeOf(user_info.get('card_create_time'))
            card_expiration_time = timeOf(user_info.get('card_expiration_time'))
            modified_time = timeOf(user_info.get('modified_time'))
            if user_info.get('stop_time'):
                stop_time = timeOf(user_info.get('stop_time'))
            else:
                stop_time = 0
            user_info.update({'card_create_time': card_create_time})
            user_info.update({'card_expiration_time': card_expiration_time})
            user_info.update({'modified_time': modified_time})
            user_info.update({'stop_time': stop_time})
            if user_info.get('flag') == 1:
                user_info.update({'flag': '卡正常'})
            else:
                user_info.update({'flag': '卡过期'})
            if user_info.get('stop_flag') == 1:
                user_info.update({'stop_flag': '卡暂停'})
            else:
                user_info.update({'stop_flag': '卡正常'})



    return render(request, 'seatManage/search.html', locals())


def stop_time(request):
    if request.POST:
        time_stop_info = request.POST
        modified_time = int(time.time())
        time_stop = time_stop_info['zDate']
        time_stop = int(time.mktime(time.strptime(time_stop[: -1].replace("T", " "), '%Y-%m-%d %H:%M')))
        # print(time_stop)
        stop_num = UserInfo.objects.values('stop_number').filter(user_card_number=time_stop_info['cNum'])
        stop_number = stop_num[0].get('stop_number') + 1
        UserInfo.objects.filter(user_card_number=time_stop_info['cNum']).update(modified_time=modified_time,
                                                                                stop_number=stop_number,
                                                                                stop_time=time_stop,
                                                                                stop_flag=1)
    return redirect(HOST+"/seatManage/manage")


def timestamp_to_time(ts):
    try:
        return int(time.mktime(time.strptime(ts[: -1].replace("T", " "), '%Y-%m-%d %H:%M')))
    except:
        return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(ts)))


def manage(request):
    users = UserInfo.objects.values('id', 'username', 'user_sex', 'user_seat_id', 'user_fingerprint',
                                    'user_card_number',
                                    'user_card_class', 'user_phone', 'card_create_time', 'card_expiration_time',
                                    'modified_time', 'stop_number', 'stop_time', 'flag','stop_flag').filter(stop_flag=1)
    users = list(users)
    for user_info in users:
        card_create_time = timeOf(user_info.get('card_create_time'))
        card_expiration_time = timeOf(user_info.get('card_expiration_time'))
        modified_time = timeOf(user_info.get('modified_time'))
        if user_info.get('stop_time'):
            stop_time = timeOf(user_info.get('stop_time'))
        else:
            stop_time = 0
        user_info.update({'card_create_time': card_create_time})
        user_info.update({'card_expiration_time': card_expiration_time})
        user_info.update({'modified_time': modified_time})
        user_info.update({'stop_time': stop_time})
        if user_info.get('flag') == 1:
            user_info.update({'flag': '卡未过期'})
        else:
            user_info.update({'flag': '卡过期'})
        if user_info.get('stop_flag') == 1:
            user_info.update({'stop_flag': '卡暂停'})
        else:
            user_info.update({'stop_flag': '卡正常'})

    return render(request, 'seatManage/manage.html', locals())


def start_time(request):
    if request.POST:

seatManage/templates/seatManage/index.html
{% extends 'seatManage/base.html' %}
{% load static %}
{% block title %} 博客首页 {% endblock %}

{% block content %}
<div class="jumbotron">
        <div class="row">
            <div class="col-xs-12 col-sm-1 col-md-1"></div>
            <div class="col-xs-12 col-sm-1 col-md-1">
                <img style="width: 160px; vertical-align: middle; text-align: center" src="{% static 'seatManage/logo.png' %}"></a>
            </div>
            <div class="col-xs-12 col-sm-1 col-md-1"></div>
            <div class="col-xs-12 col-sm-9 col-md-9">
                <form id="start_card" class="form-inline" action="{% url 'seatManage:add_user' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="Name">姓名<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="Name" placeholder="请输入姓名" name="username">
                    </div>
                    <div class="form-group">
                      <label >性别<span style="color: red">*</span></label>
                        <label>
                            <select class="form-control"  name="sex">
                              <option>请选择性别</option>
                              <option value="男">男</option>
                              <option value="女">女</option>
                            </select>
                        </label>
                    </div>
                    <div class="form-group">
                      <label for="seat">座位<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="seat" placeholder="请选择的座位号1-42" name="seat">
                    </div>
                    <div class="form-group">
                      <label for="cardClass">卡种<span style="color: red">*</span></label>
<!--                      <input type="text" class="form-control" id="cardClass" placeholder="请选择卡的类型">-->
                        <label>
                            <select class="form-control" id="cardClass" name="cardClass">
                                <option >请选择卡种</option>
                                <option>日卡</option>
                                <option>周卡</option>
                                <option>月卡</option>
                                <option>季卡</option>
                                <option>半年卡</option>
                            </select>
                        </label>
                    </div>
                    <div class="form-group">
                      <label for="fingerPrint">指纹<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="fingerPrint" placeholder="请输入指纹" name="fingerPrint">
                    </div>
                    <div class="form-group">
                      <label for="phone">电话<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="phone" placeholder="请输入电话" name="phone">
                    </div>

                    <button type="button" class="btn btn-primary"  onclick="valid()">
                        开卡
                    </button>
                    <label><span style="color: red">(带*号为必填项)</span></label>
                </form>
                <hr>
                <form class="form-inline" id="update_form" action="{% url 'seatManage:update_user' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="cardNum">卡号<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="cardNum" placeholder="请输入卡号" name="cardNum">
                    </div>

                    <div class="form-group">
                      <label for="updateSeat">座位号<span style="color: red">*</span></label>
                      <input type="text" class="form-control" id="updateSeat" placeholder="请选择的座位号1-42" name="updateSeat"><span id="err" style="color: red"></span>
                    </div>


                    <div class="form-group">
                      <label for="date">更改到期时间<span style="color: red">*</span></label>
                      <input type="datetime-local" class="form-control" id="date" placeholder="请输入日期" name="date">
                    </div>
                    <button type="button" class="btn btn-primary" onclick="sub()">更改用户信息</button>
                    <label><span style="color: red">(带*号为必填项)</span></label>
                    </form>
            </div>
        </div>
</div>


<div  class="row">
    <div class="col-md-4">
        <div class="thumbnail col-xs-12 col-sm-12 col-md-12 ">
            <img src="{% static 'seatManage/localmap.jpg' %}" alt="..." class="img-thumbnail">
            <img src="{% static 'seatManage/localmap.jpg' %}" alt="..." class="img-thumbnail">
            <img src="{% static 'seatManage/localmap.jpg' %}" alt="..." class="img-thumbnail">
            <img src="{% static 'seatManage/localmap.jpg' %}" alt="..." class="img-thumbnail">
        </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-7">
        <div class="row">
            {% for seat in seat_list %}
                <div class="col-xs-4 col-sm-3 col-md-2">
                    <div class="thumbnail">
                        {% if seat.username and seat.flag == 1 %}
                            <img src="{% static seat.img_seat_url %}" alt="..." class="img-thumbnail bg-danger">
                            <div class="caption">
                                <span style="font-size: 7px">用户：{{seat.username}}</span><br>
                                <span style="font-size: 7px">卡号：{{seat.user_card_number}}</span><br>
                                <span style="font-size: 7px">{{seat.user_card_class}}</span><br>
                                <span style="font-size: 7px">剩余 <span class="label label-primary">{{seat.rest_day}}</span> 天</span><br>
                            </div>

                        {%else%}
                            <img src="{% static seat.img_seat_url %}" alt="..." class="img-thumbnail bg-info">
                            <div class="caption">
                                <span style="font-size: 7px">您好！</span><br>
                                <span style="font-size: 7px">岸上自习室</span><br>
                                <span style="font-size: 7px">祝您顺利！</span><br>
                                <span style="font-size: 7px">成功上岸！</span><br>
                            </div>
                          {% endif %}
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
    <div class="col-md-1">
    </div>

</div>

{% endblock %}

{% block script %}

<script>
    function valid(){
        const username = $("#username").val().trim();
        const sex = $("#username").val().trim();
        const cardClass = $("#cardClass").val().trim();
        const fingerPrint = $("#fingerPrint").val().trim();
        const seat = $("#seat").val().trim();
        const mobile = $("#phone").val().trim();
        if(username==="" || sex==="" || cardClass==="" || seat === "" || fingerPrint==="" || mobile===""){
            alert("带*为必填项，请填写！");
        }

        if(seat > 42 || seat < 0 ){
            alert("座位号错误,座位号不能为空或者选择1-42之间的号码");
            return false;
        }

        const regexp = /^1\d{10}$/; // 只校验1开头，后面还有10位数字
        // var myreg=/^[1][3,4,5,7,8][0-9]{9}$/; // 校验号段，号段哪天更新了这里也要加上新号段
        if (mobile!=="" && !regexp.test(mobile)) {
            alert("手机号格式不正确！");
            return false;
        }
        else {
            $("#start_card").submit()
            alert("开卡成功")
            return true;
        }
    }

    function sub(){
        const cardNum = $("#cardNum").val().trim();
        const updateSeat = $("#updateSeat").val().trim();
        const date = $("#date").val().trim();
        if(updateSeat>43 || updateSeat<0){
            alert("输入的座位号有误，请重新输入！");
        }

        if(cardNum==="" || updateSeat==="" || date==="" ){
            alert("带*为必填项，请填写！");
        }else {
            $("#update_form").submit();
            alert("更新成功");
            return true;
        }
    }

    $("#updateSeat").blur(function (){
        const updateSeat = $(this).val();
        $.ajax({
            url:"/seatManage/vail_seat",
            data:{updateSeat:updateSeat,csrfmiddlewaretoken:'{{ csrf_token }}'},
            type:'POST',
            success:function (ret){
                console.log(ret)
                if(ret==='1'){
                    $('#err').text(updateSeat+'号座位被占，请重新选择');
                    alert(updateSeat+'号座位被占，请重新选择')

                }
            }
        });
    });


</script>
{%  endblock %}

seatManage/templates/seatManage/manage.html
{% extends 'seatManage/base.html' %}
{% load static %}
{% block title %} 博客首页 {% endblock %}

{% block content %}
<div class="jumbotron">
        <div class="row">
            <div class="col-xs-12 col-sm-1 col-md-1"></div>
            <div class="col-xs-12 col-sm-1 col-md-1">
                <img style="width: 160px; vertical-align: middle; text-align: center" src="{% static 'seatManage/logo.png' %}"></a>
            </div>
            <div class="col-xs-12 col-sm-1 col-md-1"></div>
            <div class="col-xs-12 col-sm-9 col-md-9">
                <form class="form-inline" action="{% url 'seatManage:stop_time' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="cNum">卡号</label>
                      <input type="text" class="form-control" id="cNum" placeholder="请输入卡号" name="cNum">
                    </div>

                    <div class="form-group">
                      <label for="zSeat">座位号</label>
                      <input type="text" class="form-control" id="zSeat" placeholder="请选择的座位号1-42" name="zSeat">
                    </div>

                    <div class="form-group">
                      <label for="zDate">开始暂停时间</label>
                      <input type="datetime-local" class="form-control" id="zDate" placeholder="请输入日期" name="zDate">
                    </div>
                    <button type="submit" class="btn btn-primary">暂停</button>
                    </form>
                <hr>
                <form class="form-inline" action="{% url 'seatManage:start_time' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="cNum">卡号</label>
                      <input type="text" class="form-control" id="sNum" placeholder="请输入卡号" name="sNum">
                    </div>

                    <div class="form-group">
                      <label for="zSeat">座位号</label>
                      <input type="text" class="form-control" id="sSeat" placeholder="请选择的座位号1-42" name="sSeat">
                    </div>
                    <button type="submit" class="btn btn-primary">结束暂停</button>
                    </form>
            </div>
        </div>
</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <br><br>
        {%if users%}
        <table class="table table-hover">
            <th>id</th><th>姓名</th><th>性别</th><th>座位号</th><th>指纹</th><th>卡号</th><th>卡类</th><th>电话</th><th>开卡时间</th>
            <th>过期时间</th><th>最后修改时间</th><th>卡状态</th><th>暂停次数</th><th>暂停时间</th><th>标志</th>
           {% for u in users %}
                <tr>
                    <td>{{u.id}}</td>
                    <td>{{u.username}}</td>
                    <td>{{u.user_sex}}</td>
                    <td>{{u.user_seat_id}}</td>
                    <td>{{u.user_fingerprint}}</td>
                    <td>{{u.user_card_number}}</td>
                    <td>{{u.user_card_class}}</td>
                    <td>{{u.user_phone}}</td>
                    <td>{{u.card_create_time}}</td>
                    <td>{{u.card_expiration_time}}</td>
                    <td>{{u.modified_time}}</td>
                    <td>{{u.stop_flag}}</td>
                    <td>{{u.stop_number}}</td>
                    <td>{{u.stop_time}}</td>
                    <td>{{u.flag}}</td>
                </tr>
            {%endfor%}
        </table>
        {%else%}
        <h3>没有暂停的用户</h3>
        {%endif%}

    </div>

    <div class="col-md-1"></div>
</div>
{% endblock %}

seatManage/templates/seatManage/search.html
{% extends 'seatManage/base.html' %}
{% load static %}
{% block title %} 博客首页 {% endblock %}

{% block content %}

<div class="breadcrumb alert alert-info">

        <li><a href="#">查询所有用户信息</a></li>

</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="col-md-9"></div>
        <div class="col-md-3">
            <form class="navbar-form navbar-left" action="{% url 'seatManage:search' %}" method="post">
                {% csrf_token %}
                <input type="text" class="form-control" placeholder="请输入查询的卡号" name="cardNum">
                <button type="submit" class="btn btn-default">查询</button>
            </form>
        </div>
        <br><br>
        {%if user%}
        <table class="table table-hover">
            <th>id</th><th>姓名</th><th>性别</th><th>座位号</th><th>指纹</th><th>卡号</th><th>卡类</th><th>电话</th><th>开卡时间</th>
            <th>过期时间</th><th>最后修改时间</th><th>卡状态</th><th>暂停次数</th><th>暂停时间</th><th>标志</th>
           {% for u in user %}
                    <tr>
                        <td>{{u.id}}</td>
                        <td>{{u.username}}</td>
                        <td>{{u.user_sex}}</td>
                        <td>{{u.user_seat_id}}</td>
                        <td>{{u.user_fingerprint}}</td>
                        <td>{{u.user_card_number}}</td>
                        <td>{{u.user_card_class}}</td>
                        <td>{{u.user_phone}}</td>
                        <td>{{u.card_create_time}}</td>
                        <td>{{u.card_expiration_time}}</td>
                        <td>{{u.modified_time}}</td>
                        <td >{{u.stop_flag}}</td>
                        <td>{{u.stop_number}}</td>
                        <td>{{u.stop_time}}</td>
                        <td>{{u.flag}}</td>
                    </tr>
                {%endfor%}
                {%else%}
                <h3>查询的数据不存在</h3>
        </table>
        {%endif%}

    </div>

    <div class="col-md-1"></div>
</div>
<!--</div>-->


{% endblock %}

seatManage/templates/seatManage/userinfo.html
{% extends 'seatManage/base.html' %}
{% load static %}
{% block title %} 博客首页 {% endblock %}

{% block content %}

<div class="breadcrumb alert alert-info">

        <li><a href="#">查询所有用户信息</a></li>

</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="col-md-9"></div>
        <div class="col-md-3">
            <form class="navbar-form navbar-left" action="{% url 'seatManage:search' %}" method="post">
                {% csrf_token %}
                <input type="text" class="form-control" placeholder="请输入查询的卡号" name="cardNum">
                <button type="submit" class="btn btn-default">查询</button>
            </form>
        </div>
        <br><br>
        {%if users%}
        <table class="table table-hover">
            <th>id</th><th>姓名</th><th>性别</th><th>座位号</th><th>指纹</th><th>卡号</th><th>卡类</th><th>电话</th><th>开卡时间</th>
            <th>过期时间</th><th>最后修改时间</th><th>卡状态</th><th>暂停次数</th><th>暂停时间</th><th>标志</th>
                {% for user_info in users %}
                <tr>
                    <td>{{user_info.id}}</td>
                    <td>{{user_info.username}}</td>
                    <td>{{user_info.user_sex}}</td>
                    <td>{{user_info.user_seat_id}}</td>
                    <td>{{user_info.user_fingerprint}}</td>
                    <td>{{user_info.user_card_number}}</td>
                    <td>{{user_info.user_card_class}}</td>
                    <td>{{user_info.user_phone}}</td>
                    <td>{{user_info.card_create_time}}</td>
                    <td>{{user_info.card_expiration_time}}</td>
                    <td>{{user_info.modified_time}}</td>
                    <td>{{u.stop_flag}}</td>
                    <td>{{user_info.stop_number}}</td>
                    <td>{{user_info.stop_time}}</td>
                    <td>{{user_info.flag}}</td>
                </tr>
                {% endfor %}
        </table>
        {%else%}
        <h3>数据不存在</h3>
        {%endif%}



    </div>

    <div class="col-md-1"></div>
</div>
<!--</div>-->


{% endblock %}